//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalievLanguageSchool
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.IO;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }

        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string GenderCode { get; set; }
        public string Phone { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }

        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
        public string LastVisitDate
        {
            get
            {
                // Нам не нужно фильтровать по ID, так как коллекция уже принадлежит этому клиенту
                var lastVisit = ClientService
                    .OrderByDescending(p => p.StartTime)
                    .FirstOrDefault();

                if (lastVisit == null)
                    return "нет";

                return $"Дата последнего посещения: {lastVisit.StartTime:dd.MM.yyyy}";
            }
        }
        public string FIO
        {
            get
            {
                return $"{FirstName} {LastName} {Patronymic}".Trim();
            }
        }
        public int TotalVisits
        {
            get
            {
                return ClientService.Count;
            }
        }

        public string FullPhotoPath
        {
            get
            {
                // Если в базе пусто или записано "Клиенты" без имени файла
                if (string.IsNullOrWhiteSpace(PhotoPath) || PhotoPath.Trim() == "Клиенты")
                {
                    return null;
                }

                // Склеиваем путь к папке приложения и путь из базы
                string fullPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, PhotoPath);

                // Проверяем, существует ли файл физически на диске
                if (File.Exists(fullPath))
                {
                    return fullPath;
                }

                return null; // Если файла нет, возвращаем null (картинка будет пустой)
            }
        }
    }
}

